//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by hight map gl.rc
//
#define IDOK                            1
#define IDC_MYICON                      2
#define IDD_HIGHTMAPGL_DIALOG           102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDC_MENU_DATA_1                 104
#define IDM_EXIT                        105
#define IDI_HIGHTMAPGL                  107
#define IDI_SMALL                       108
#define IDC_HIGHTMAPGL                  109
#define ID_DATA_COUNTSPOTS_1            110
#define ID_DATA_COUNTSPOTS_2            111
#define ID_DATA_COUNTSPOTS_3            112
#define ID_DATA_COUNTSPOTS_4            113
#define ID_DATA_COUNTSPOTS_5            114
#define ID_DATA_COUNTSPOTS_6            115
#define ID_DATA_COUNTSPOTS_7            116
#define ID_DATA_COUNTSPOTS_8            117
#define ID_DATA_COUNTSPOTS_9            118
#define ID_DATA_COUNTSPOTS_10           119
#define ID_DATA_SHOWDATA_1              120
#define ID_DATA_SHOWDATA_2              121
#define ID_DATA_SHOWDATA_3              122
#define ID_DATA_SHOWDATA_4              123
#define ID_DATA_SHOWDATA_5              124
#define ID_DATA_SHOWDATA_6              125
#define ID_DATA_SHOWDATA_7              126
#define ID_DATA_SHOWDATA_8              127
#define IDR_MAINFRAME                   128
#define ID_DATA_SHOWDATA_9              128
#define IDR_HISTOGRAMM_MENU             128
#define IDD_SETTINGS                    129
#define ID_DATA_SHOWDATA_10             129
#define ID_DATA_CLOSE_1                 130
#define ID_DATA_CLOSE_2                 131
#define ID_DATA_CLOSE_4                 132
#define IDD_SPOTS_INFO                  133
#define ID_DATA_CLOSE_3                 133
#define IDD_SPOTINFO                    134
#define ID_DATA_CLOSE_5                 134
#define IDD_IMAGE_SETTINGS              135
#define ID_DATA_CLOSE_6                 135
#define IDC_SPOT_DISPLAY_MENU           136
#define ID_DATA_CLOSE_7                 136
#define ID_DATA_CLOSE_8                 137
#define ID_DATA_CLOSE_9                 138
#define IDD_HISTOGRAMMSETTINGS          138
#define ID_DATA_CLOSE_10                139
#define ID_DATA_SHOWHISTOGRAMM_1        140
#define IDD_AREAHEIGHT_SETTINGS         140
#define ID_DATA_SHOWHISTOGRAMM_2        141
#define IDR_AREAHEIGHT_MENU             141
#define ID_DATA_SHOWHISTOGRAMM_3        142
#define ID_DATA_SHOWHISTOGRAMM_4        143
#define ID_DATA_SHOWHISTOGRAMM_5        144
#define ID_DATA_SHOWHISTOGRAMM_6        145
#define ID_DATA_SHOWHISTOGRAMM_7        146
#define ID_DATA_SHOWHISTOGRAMM_8        147
#define ID_DATA_SHOWHISTOGRAMM_9        148
#define ID_DATA_SHOWHISTOGRAMM_10       149
#define ID_DATA_SHOWAREAHEIGHT_1        150
#define ID_DATA_SHOWAREAHEIGHT_2        151
#define ID_DATA_SHOWAREAHEIGHT_3        152
#define ID_DATA_SHOWAREAHEIGHT_4        153
#define ID_DATA_SHOWAREAHEIGHT_5        154
#define ID_DATA_SHOWAREAHEIGHT_6        155
#define ID_DATA_SHOWAREAHEIGHT_7        156
#define ID_DATA_SHOWAREAHEIGHT_8        157
#define ID_DATA_SHOWAREAHEIGHT_9        158
#define ID_DATA_SHOWAREAHEIGHT_10       159
#define IDC_SETTINGS_HIGHT              1000
#define IDC_SETTINGS_SURROUNDING        1005
#define IDC_SETTINGS_SET                1008
#define IDC_SETTINGS_CLOSE              1009
#define IDC_SETTINGS_MIN_HIGHT          1010
#define IDC_SETTINGS_MIN_AREA           1011
#define IDC_SPOT_INFO_AVeRIGE_AREA      1012
#define IDC_SPOT_INFO_AVeRIGE_HIGHT     1013
#define IDC_SPOT_INFO_AKTIV_SPOTS       1014
#define IDC_SPOT_INFO_COUNTED_SPOTS     1015
#define IDC_SPOTINFO_UPDATE             1016
#define IDC_SPOTSINFO_VOLUM             1017
#define IDC_SPOTINFO_ID                 1019
#define IDC_SPOTINFO_HIGHT              1020
#define IDC_SPOTINFO_AREA               1021
#define IDC_RANGE                       1022
#define IDC_OFFSET                      1023
#define IDC_REDUCEDVOLME                1024
#define IDC_CAPTION                     1025
#define IDC_3D_RANGE                    1026
#define IDC_BIN_NUMBER                  1028
#define IDC_MAXIMUM_HEIGHT              1029
#define IDC_AREAHEIGHT_MAX_HEIGHT       1029
#define IDC_MINIMUM_HEIGHT              1030
#define IDC_AREAHEIGHT_MIN_HEIGHT       1030
#define IDC_YRANGE                      1031
#define IDC_AREAHEIGHT_MAX_AREA         1031
#define IDC_AEAHEIGHT_MIN_AREA          1032
#define IDC_AREAHEIGHT_FIT_AREA         1033
#define IDC_AREAHEIGHT_ERROR_MULTIPLIER 1034
#define ID_DATEI_OPEN                   32771
#define ID_DATA_SAVEHIGHTS              32772
#define ID_DATA_COUNTSPOTS              32773
#define ID_DATA_SETTINGS                32774
#define ID_DATA_SPOTINFO                32775
#define ID_DATA_SPOTSINFO               32776
#define ID_DATA_SPOTINFO32777           32777
#define ID_DATA_SAVEAKTIVEHIGHTS        32778
#define ID_DATA_SETTINGS_SAVEAKTIVHIGHTS 32779
#define ID_FILE_SAVE                    32780
#define ID_SAVE_SAVEAREAS               32781
#define ID_SAVE_SAVEAKTIVAREAS          32782
#define ID_DISPLAY_DATA                 32783
#define ID_DISPLAY_AREA                 32784
#define ID_DISPLAY_COUNTETSPOTS         32785
#define ID_DATA_IMAGESETTINGS           32786
#define ID_DISPLAY_MASK                 32787
#define ID_DISPLAY_DATA32788            32788
#define ID_DISPLAY_COUNTETSPOTS32789    32789
#define ID_DISPLAY_MASK32790            32790
#define ID_DATA_SPOTSINFO32791          32791
#define ID_DATA_SPOTINFO32792           32792
#define ID_DATA_IMAGESETTINGS32793      32793
#define ID_SAVE_SAVEHIGHTS              32794
#define ID_SAVE_ACTIVEHIGHTS            32795
#define ID_SAVE_AREA                    32796
#define ID_SAVE_ACTIVEAREA              32797
#define ID_DATA_IMAGE_SETTINGS          32798
#define ID_DATA                         32799
#define ID_DATA_TE                      32800
#define ID_DATA_COUNT_ALL               32801
#define ID_DISPLAY_3D                   32802
#define ID_SAVE_ALLHEIGHTS              32803
#define ID_SAVE_AKTIVEHEIGHTS           32804
#define ID_SAVE_ALLAREAS                32805
#define ID_SAVE_AKTIVEAREAS             32806
#define ID_SAVE_HEIGHTS                 32807
#define ID_DATA_SETTINGS32808           32808
#define ID_DATA_HISTOGRAMMSETTING       32809
#define ID_FILE_SETTINGS                32810
#define ID_FILE_AREAHEIGHT_SETTINGS     32811
#define ID_ALL_SAVEALLDATA              32812
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         32813
#define _APS_NEXT_CONTROL_VALUE         1030
#define _APS_NEXT_SYMED_VALUE           160
#endif
#endif
